###
GET http://localhost:3000/api/applicants

###
GET http://localhost:3000/api/applicants?projectId=_c5w7cuzec

###
GET http://localhost:3000/api/applicants?freelancerId=_ig11hcoez

###
GET http://localhost:3000/api/applicants?projectId=_c5w7cuzec&freelancerId=_ig11hcoez

###
GET http://localhost:3000/api/applicants/projects/_ig11hcoez

###
GET http://localhost:3000/api/applicants/freelancers/_c5w7cuzec

###
DELETE http://localhost:3000/api/applicants

###
DELETE http://localhost:3000/api/applicants/project/c5w7cuzec

###
DELETE http://localhost:3000/api/applicants/freelancer/j92psyqo7

###
POST http://localhost:3000/api/applicants
content-type: application/json

{
	"projectId": "_c5w7cuzec", 
	"freelancerId": "_j92psyqo7"
	
}

###
POST http://localhost:3000/api/applicants
content-type: application/json

{
	"projectId": "_61en2nr6a", 
	"freelancerId": "_j92psyqo7"
	
}

###
POST http://localhost:3000/api/applicants
content-type: application/json

{
	"projectId": "_kuskoisuwy", 
	"freelancerId": "_j92psyqo7"
	
}

###
POST http://localhost:3000/api/applicants
content-type: application/json

{
	"projectId": "_61en2nr6a", 
	"freelancerId": "_ig11hcoez"
	
}

###
POST http://localhost:3000/api/applicants
content-type: application/json

{
	"projectId": "_c5w7cuzec", 
	"freelancerId": "_ig11hcoez"
	
}

###
_c5w7cuzec
_61en2nr6a
_kuskoisuwy

_j92psyqo7
_ig11hcoez